### ISSUE TITLE
Integrate with Contacts and My People

### ISSUE THREAD

**Issue by xperiandri** [MahStudio/Winsta#85]
It would be nice to chat with contacts using My People integration

**Comment by NGame1** [comment]
My people feature is just got obsolete and no longer maintained. 
I also took a look on it before but seems it's not possible to be integrated with Winsta, My people integration needs integrating contacts with your contacts. I can't link your followers/followings with your contacts because normally we don't have access to Instagram users Phone number, Email address or etc.
